export const PRIVACY_POLICY_HTML = `<h1>Privacy Policy</h1>
<p>Last updated: June 19, 2026</p>
<p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
<p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank">Privacy Policy Generator</a>.</p>
<h2>Interpretation and Definitions</h2>
<h3>Interpretation</h3>
<p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
<h3>Definitions</h3>
<p>For the purposes of this Privacy Policy:</p>
<ul>
<li>
<p><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</p>
</li>
<li>
<p><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</p>
</li>
<li>
<p><strong>Application</strong> refers to VibeNMED, the mobile application provided by the Company.</p>
</li>
<li>
<p><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to CloudDropDesigns LLC.</p>
</li>
<li>
<p><strong>Country</strong> refers to: California,  United States</p>
</li>
<li>
<p><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</p>
</li>
<li>
<p><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</p>
</li>
<li>
<p><strong>Service</strong> refers to the Application.</p>
</li>
<li>
<p><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</p>
</li>
<li>
<p><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</p>
</li>
<li>
<p><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</p>
</li>
</ul>
<h2>Collecting and Using Your Personal Data</h2>
<h3>Types of Data Collected</h3>
<h4>Personal Data</h4>
<p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
<ul>
<li>
<p>Email address, phone number, and account identifiers</p>
</li>
<li>
<p>First name and last name, profile details, and professional information</p>
</li>
<li>
<p>Photos, verification documents, and messages you submit in the App</p>
</li>
<li>
<p>Approximate location (when you grant permission)</p>
</li>
<li>
<p>Usage Data and device identifiers</p>
</li>
</ul>
<h4>Usage Data</h4>
<p>Usage Data is collected automatically when using the Service.</p>
<p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
<p>When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
<p>We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.</p>
<h4>Information Collected while Using the Application</h4>
<p>While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission:</p>
<ul>
<li>
<p>Information regarding your location</p>
</li>
<li>
<p>Pictures and other information from your Device's camera and photo library</p>
</li>
</ul>
<p>We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company's servers and/or a Service Provider's server or it may be simply stored on Your device.</p>
<p>You can enable or disable access to this information at any time, through Your Device settings.</p>
<h3>Use of Your Personal Data</h3>
<p>The Company may use Personal Data for the following purposes:</p>
<ul>
<li>
<p><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</p>
</li>
<li>
<p><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</p>
</li>
<li>
<p><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</p>
</li>
<li>
<p><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</p>
</li>
<li>
<p><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about unless You have opted not to receive such information.</p>
</li>
<li>
<p><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</p>
</li>
<li>
<p><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</p>
</li>
<li>
<p><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</p>
</li>
</ul>
<p>We may share Your personal information in the following situations:</p>
<ul>
<li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service,  to contact You.</li>
<li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
<li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
<li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
<li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
<li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
</ul>
<h3>Retention of Your Personal Data</h3>
<p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
<p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.</p>
<h3>Transfer of Your Personal Data</h3>
<p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
<p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
<p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
<h3>Delete Your Personal Data</h3>
<p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
<p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
<p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
<p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
<h3>Disclosure of Your Personal Data</h3>
<h4>Business Transactions</h4>
<p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
<h4>Law enforcement</h4>
<p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
<h4>Other legal requirements</h4>
<p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
<ul>
<li>Comply with a legal obligation</li>
<li>Protect and defend the rights or property of the Company</li>
<li>Prevent or investigate possible wrongdoing in connection with the Service</li>
<li>Protect the personal safety of Users of the Service or the public</li>
<li>Protect against legal liability</li>
</ul>
<h3>Security of Your Personal Data</h3>
<p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
<h2>Children's Privacy</h2>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h2>Links to Other Websites</h2>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
<h2>Third-Party Services</h2>
<p>VibeNMED uses the following third-party services to operate the App. Each provider processes data according to its own privacy policy:</p>
<ul>
<li><strong>Google Firebase</strong> (authentication, cloud database, file storage, and server functions) — <a href="https://firebase.google.com/support/privacy" target="_blank">Firebase Privacy</a></li>
<li><strong>Google Sign-In</strong> (optional account sign-in) — <a href="https://policies.google.com/privacy" target="_blank">Google Privacy Policy</a></li>
<li><strong>Sign in with Apple</strong> (optional account sign-in on iOS) — <a href="https://www.apple.com/legal/privacy/" target="_blank">Apple Privacy Policy</a></li>
<li><strong>Stream Chat</strong> (in-app messaging between matched users) — <a href="https://getstream.io/privacy/" target="_blank">Stream Privacy Policy</a></li>
<li><strong>Expo Push Notifications</strong> (device push notification delivery) — <a href="https://expo.dev/privacy" target="_blank">Expo Privacy Policy</a></li>
<li><strong>Amazon</strong> (affiliate product links in the in-app shop; purchases occur on Amazon's website) — <a href="https://www.amazon.com/gp/help/customer/display.html?nodeId=468496" target="_blank">Amazon Privacy Notice</a></li>
</ul>
<p>We may collect and process: account identifiers, profile information, photos and verification documents you upload, approximate location (with your permission), messages you send through the App, safety reports, device identifiers, and push notification tokens. You can delete your account and associated data from within the App.</p>
<h2>Changes to this Privacy Policy</h2>
<p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
<p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
<h2>Contact Us</h2>
<p>If you have any questions about this Privacy Policy, You can contact us:</p>
<ul>
<li>By email: cloud@clouddropdesigns.com</li>
</ul>`;

export const TERMS_OF_SERVICE_HTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - VibeNMED</title>
    <style>
        /* Document Setup */
        body {
            background-color: #f9f9f9;
            margin: 0;
            padding: 40px;
            display: flex;
            justify-content: center;
        }

        .container {
            background: #ffffff;
            max-width: 800px;
            padding: 50px;
            box-shadow: 0 4px 15px rgba(0,0,0,0.05);
            border-radius: 8px;
        }

        /* The SVG Header Logo */
        .header-logo {
            display: block;
            margin: 0 auto 50px;
            width: 178px;
            height: 38px;
            background: url("data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIxNzgiIGhlaWdodD0iMzgiIHZpZXdCb3g9IjAgMCAxNzggMzgiPgogICAgPGcgZmlsbD0ibm9uZSIgZmlsbC1ydWxlPSJldmVub2RkIj4KICAgICAgICA8cGF0aCBmaWxsPSIjRDFEMUQxIiBkPSJNNC4yODMgMjQuMTA3Yy0uNzA1IDAtMS4yNTgtLjI1Ni0xLjY2LS43NjhoLS4wODVjLjA1Ny41MDIuMDg2Ljc5Mi4wODYuODd2Mi40MzRILjk4NXYtOC42NDhoMS4zMzJsLjIzMS43NzloLjA3NmMuMzgzLS41OTQuOTUtLjg52Ljg1Mi0uNDQzem01LjU3IDEuNzk0YzAgLjU5NC4wOTggMS4wNDQuMjkzIDEuMzQ4LjE5Ni4zMDQuNTEzLjE5Mi0uMzAzLjI4OC0uNzUzLjI4OC0xLjM1MSAwLS41OTUtLjA5Ny0xLjA0LS4yOS0xLjMzOC0uMTk0LS4yOTctLjUxLS40NDUtLjk1LS40NDUtLjQzOCAwLS43NTMuMTQ3LS45NDYuNDQzLS4xOTQtLjI5NS0uMjkuNzQyLS4yOSAxLjM0em00LjE1MyAwYzAgLjk3Ny0uMjU4IDEuNzQyLS43NzQgMi4yOTMtLjUxNS41NTItMS4yMzMuODI3LTIuMTU0LjgyNy0uNzA1IDAtMS4yNTgtLjI1Ni0xLjY1OS0uNzY4aC0uMTEzbC0uMjc0LjY2MWgtMS4yNTF2LTguMzU3aDEuNjM4djEuOTQ0YzAgLjI0Ny0uMDIxLjY0My0uMDY0IDEuMTg3aC4wNjRjLjM4My0uNTk0Ljk1LS44OTIgMS43MDMtLjg5MnptLS41MjcgMS4zMWMtLjQwNCAwLS43LjE5OS0uMzEuMjk4LS43Ni4yOTgtMS4zNSAwLS41OTEtLjEtMS4wMzUtLjMtMS4zM2EuOTQzLjk0MyIDAgMCAwLS44MjMtLjQ0M3ptMy4xODYtMS4xOTdoMS43OTRsMS4xMzQgMy4zNzljLjA5Ni4yOTMuMTYzLjY0LjE5OCAxLjA0MmguMDMzYy4wMzktLjM3LjExNi0uNzE3LjIzLS40MzIuMzEyLS45MzYuNDY4LTEuNTEyLjQ2OC0uMjgzIDAtLjU2LS4wMzUtMi4zODUtNS45NjJ6Ii8+CiAgICAgICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNzMpIj4KICAgICAgICAgICAgPGNpcmNsZSBjeD0iMTkiIGN5PSIxOSIgcj0iMTkiIGZpbGw9IiNFMEUwRTAiLz4KICAgICAgICAgICAgPHBhdGggZmlsbD0iI0ZGRiIgZD0iTTIyLjQ3NCAxNS40NDNoNS4xNjJMMTIuNDM2IDMwLjRWMTAuMzYzaDE1LjJsLTUuMTYyIDUuMDh6Ii8+CiAgICAgICAgPC9nPgogICAgICAgIDxwYXRoIGZpbGw9IiNEMkQyRDIiIGQ9Ik0xMjEuNTQ0IDE0LjU2di0xLjcyOGg4LjI3MnYxLjcyOGgtMy4wMjRWMjRoLTIuMjR2LTkuNDRoLTMuMDA4em0xMy43NDQgOS41NjhjLTEuMjkgMC0yLjM0MS0uNDI0IDEuNDI0LjUzNC0uOTY2IDAtMS43MjItLjI2Ny0yLjI2Ni0uOC0uNTQ0LS41MzQtLjgxNi0xLjI5LS44MTYtMi4yNjcgMC0xLjAwNy4yNTEtMS43ODUuNzU0LTIuMzM0LjUwMy0uNTUgMS4xOTktLjgyNSAyLjA4Ny0uODI1Ljg0OCAwIDEuNTEuMjQyIDEuOTgyLjcyNS40NzIuNDg0LjcwOSAxLjE1Mi43MDkgMi4wMDR2Ljc5NWgtMy44NzNjLjAxOC40NjUuMTU2LjgyOS40MTQgMS4wOS4yNTguMjYxLjYyLjM5MiAxLjA4NS4zOTIuMzYxIDAtLjcwMy0uMDM3IDEuMDI2LS4xMTNhNS4xMzMgNS4xMzMgMCAwIDAgMS4wMS0uMzZ2MS4yNjhjLS4yODcuMTQzLS41OTMuMjUtLjkyLjMyYTUuNzkgNS43OSAwIDAgMS0xLjE5MS4xMDR6bTcuMDU2IDEuNzM2VjI0aC0yLjI1NnYtOC44NjRoMi4yNTZ6TTE2NC45MzYgMjRWMTIuMGEzLjg5MSAzLjg5MSAwIDAgMS0xLjQ4OCAyLjA2NGMtLjczNi41MzMtMS42MjcuOC0yLjY3Mi44em0xLjQ4LTMuNjg4Yy0uNC0uMzUyLS44ODMtLjUyOC0xLjQ0OC0uNTI4cy0xLjAzNy4xNzYtMS40MTYuNTI4Yy0uMzc5LjM1Mi0uNjA1LjgyMS0uNjggMS40MDhoNC4xOTJjLS4wMzItLjU4Ny0uMjQ4LTEuMDU2LS42NDgtMS40MDh6bTcuMDE2LTIuMzA0djEuNTY4Yy41OTctMS4xMyAxLjQ2MS0xLjY5NiAyLjU5Mi0xLjY5NnYyLjMwNGgtLjU2Yy0uNjcyIDAtMS4xNzkuMTY4LTEuNTIuNTA0LS4zNDEuMzM2LS41MTIuOTE1LS41MTIgMS43MzZWMjRoLTIuMjU2di04Ljg2NGgyLjI1NnpNMTY0LjkzNiAyNFYxMi4xNmgyLjI1NlYyNGgtMi4yNTZ6bTcuMDQtLjE2bC0zLjQ3Mi04LjcwNGgyLjUyOGwyLjI1NiA2LjMwNCAyLjM4NC02LjMwNGgyLjM1MmwtNS41MzYgMTMuMDU2aC0yLjM1MmwxLjg0LTQuMzUyeiIvPgogICAgPC9nPgo8L3N2Zz4=") no-repeat center;
        }

        /* Standard Text Classes */
        [data-custom-class='body'] {
            font-family: 'Arial', sans-serif;
            color: #595959;
            line-height: 1.6;
        }

        [data-custom-class='title'] {
            font-size: 26px;
            color: #000000;
            font-weight: bold;
            margin-bottom: 5px;
        }

        [data-custom-class='subtitle'] {
            font-size: 14px;
            color: #777;
            margin-bottom: 25px;
        }

        [data-custom-class='heading_1'] {
            font-size: 19px;
            color: #000000;
            font-weight: bold;
            margin-top: 30px;
            border-bottom: 1px solid #eee;
            padding-bottom: 10px;
        }

        [data-custom-class='body_text'] {
            font-size: 14px;
            margin-bottom: 15px;
        }

        [data-custom-class='link'] {
            color: #3030F1;
            text-decoration: none;
            font-weight: 500;
        }

        [data-custom-class='link']:hover {
            text-decoration: underline;
        }

        /* Table of Contents List Styling */
        ol {
            padding-left: 20px;
        }

        li {
            margin-bottom: 8px;
        }
    </style>
</head>
<body>

<div class="container">
    <div class="header-logo"></div>

    <div data-custom-class="body">
        <div data-custom-class="title">TERMS AND CONDITIONS</div>
        <div data-custom-class="subtitle">Last updated June 19, 2026</div>

        <div data-custom-class="heading_1">AGREEMENT TO OUR LEGAL TERMS</div>
        
        <div data-custom-class="body_text">
            We are <strong>CloudDropDesigns</strong> ("Company," "we," "us," "our"), a company registered in California, United States.
        </div>

        <div data-custom-class="body_text">
            We operate the mobile application <strong>VibeNMED</strong> (the "App"), as well as any other related products and services that refer or link to these legal terms (the "Legal Terms") (collectively, the "Services").
        </div>

        <div data-custom-class="body_text">
            You can contact us by email at <a href="mailto:cloud@clouddropdesigns.com" data-custom-class="link">cloud@clouddropdesigns.com</a>
        </div>

        <div data-custom-class="heading_1">TABLE OF CONTENTS</div>
        <ol>
            <li><a href="#services" data-custom-class="link">OUR SERVICES</a></li>
            <li><a href="#ip" data-custom-class="link">INTELLECTUAL PROPERTY RIGHTS</a></li>
            <li><a href="#userreps" data-custom-class="link">USER REPRESENTATIONS</a></li>
            <li><a href="#contact" data-custom-class="link">CONTACT US</a></li>
        </ol>

        <div id="services" data-custom-class="heading_1">1. OUR SERVICES</div>
        <div data-custom-class="body_text">
            The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation.
        </div>

        <div id="contact" data-custom-class="heading_1">26. CONTACT US</div>
        <div data-custom-class="body_text">
            In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:
        </div>
        <div data-custom-class="body_text">
            <strong>CloudDropDesigns</strong><br>
            Email: <a href="mailto:cloud@clouddropdesigns.com" data-custom-class="link">cloud@clouddropdesigns.com</a>
        </div>
    </div>
</div>

</body>
</html>`;

/** Inner body markup for web rendering (excludes document wrapper/styles). */
export const TERMS_BODY_HTML = `
        <div data-custom-class="title">TERMS AND CONDITIONS</div>
        <div data-custom-class="subtitle">Last updated June 19, 2026</div>

        <div data-custom-class="heading_1">AGREEMENT TO OUR LEGAL TERMS</div>
        
        <div data-custom-class="body_text">
            We are <strong>CloudDropDesigns</strong> ("Company," "we," "us," "our"), a company registered in California, United States.
        </div>

        <div data-custom-class="body_text">
            We operate the mobile application <strong>VibeNMED</strong> (the "App"), as well as any other related products and services that refer or link to these legal terms (the "Legal Terms") (collectively, the "Services").
        </div>

        <div data-custom-class="body_text">
            You can contact us by email at <a href="mailto:cloud@clouddropdesigns.com" data-custom-class="link">cloud@clouddropdesigns.com</a>
        </div>

        <div data-custom-class="heading_1">TABLE OF CONTENTS</div>
        <ol>
            <li><a href="#services" data-custom-class="link">OUR SERVICES</a></li>
            <li><a href="#ip" data-custom-class="link">INTELLECTUAL PROPERTY RIGHTS</a></li>
            <li><a href="#userreps" data-custom-class="link">USER REPRESENTATIONS</a></li>
            <li><a href="#contact" data-custom-class="link">CONTACT US</a></li>
        </ol>

        <div id="services" data-custom-class="heading_1">1. OUR SERVICES</div>
        <div data-custom-class="body_text">
            The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation.
        </div>

        <div id="contact" data-custom-class="heading_1">26. CONTACT US</div>
        <div data-custom-class="body_text">
            In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:
        </div>
        <div data-custom-class="body_text">
            <strong>CloudDropDesigns</strong><br>
            Email: <a href="mailto:cloud@clouddropdesigns.com" data-custom-class="link">cloud@clouddropdesigns.com</a>
        </div>`;
